name: Deploy to Render

on:
  push:
    branches:
      - main  # Esto asegura que el flujo de trabajo se ejecute solo cuando haya cambios en la rama "main"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Git
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Autenticar con Personal Access Token
        env:
          GH_PAT: ${{ secrets.GH_PAT }}  # Asegúrate de que este secreto esté bien configurado
        run: |
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/JoseGuarnizo/NttDataTest.git
          git commit --allow-empty -m "Trigger Render Deployment"
          git push origin main
