name: SonarQube and Deploy to Render

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build_and_analyze:
    name: Build and analyze with Sonar and deploy with Render
    runs-on: windows-latest
    steps:
      # Configura el JDK necesario
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu' # Alternativa de distribución

      # Clona el repositorio
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Evita clones superficiales para análisis completos

      # Cache de paquetes de SonarQube
      - name: Cache SonarQube Cloud packages
        uses: actions/cache@v4
        with:
          path: ~\sonar\cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      # Cache de SonarQube Scanner
      - name: Cache SonarQube Cloud scanner
        id: cache-sonar-scanner
        uses: actions/cache@v4
        with:
          path: .\.sonar\scanner
          key: ${{ runner.os }}-sonar-scanner
          restore-keys: ${{ runner.os }}-sonar-scanner

      # Instala el SonarScanner solo si no está en cache
      - name: Install SonarQube Cloud scanner
        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
        shell: powershell
        run: |
          New-Item -Path .\.sonar\scanner -ItemType Directory
          dotnet tool update dotnet-sonarscanner --tool-path .\.sonar\scanner

      # Construye el proyecto y realiza el análisis con SonarCloud
      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        shell: powershell
        run: |
          # Especifica la ruta al archivo .sln correctamente
          .\.sonar\scanner\dotnet-sonarscanner begin /k:"JoseGuarnizo_NttDataTest" /o:"joseguarnizo" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io"
          dotnet build TestApiNttData/TestApiNttData.sln  # Especifica la ruta al archivo .sln
          .\.sonar\scanner\dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
  
  deploy_to_render:
    name: Deploy to Render
    runs-on: ubuntu-latest
    needs: build_and_analyze  # Asegura que el despliegue solo ocurra después del análisis
    steps:
      # Clonar el repositorio
      - name: Checkout repository
        uses: actions/checkout@v4

      # Paso 1: Configurar Render CLI
      - name: Set up Render CLI
        run: |
          curl -fsSL https://cdn.render.com/cli/install.sh | bash
          echo "${{ secrets.RENDER_API_KEY }}" | render login --api-key

      # Paso 2: Desplegar en Render
      - name: Deploy to Render
        run: |
          render deploy --service ${RENDER_SERVICE_ID}
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
