name: Deployment NttDataTest

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build_and_analyze:
    name: Build, Test and Analyze
    runs-on: windows-latest
    steps:
      # Configura el JDK necesario
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu' # Alternativa de distribución

      # Clona el repositorio
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Evita clones superficiales para análisis completos

      # Cache de paquetes de SonarQube
      - name: Cache SonarQube Cloud packages
        uses: actions/cache@v4
        with:
          path: ~\sonar\cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      # Cache de SonarQube Scanner
      - name: Cache SonarQube Cloud scanner
        id: cache-sonar-scanner
        uses: actions/cache@v4
        with:
          path: .\.sonar\scanner
          key: ${{ runner.os }}-sonar-scanner
          restore-keys: ${{ runner.os }}-sonar-scanner

      # Instala el SonarQube Cloud scanner solo si no está en cache
      - name: Install SonarQube Cloud scanner
        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
        shell: powershell
        run: |
          New-Item -Path .\.sonar\scanner -ItemType Directory
          dotnet tool update dotnet-sonarscanner --tool-path .\.sonar\scanner

      # Etapa de Build (Compilación del proyecto)
      - name: Build the project
        run: |
          dotnet build TestApiNttData/TestApiNttData.sln  # Especifica la ruta

      # Etapa de Test (Ejecutar pruebas)
      - name: Run tests
        run: |
          dotnet test TestApiNttData/TestApiNttData.sln --logger "trx"  # Especifica la ruta y usa el logger TRX para ver resultados

      # Realiza el análisis con SonarCloud
      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        shell: powershell
        run: |
          # Especifica la ruta al archivo .sln correctamente
          .\.sonar\scanner\dotnet-sonarscanner begin /k:"JoseGuarnizo_NttDataTest" /o:"joseguarnizo" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io"
          dotnet build TestApiNttData/TestApiNttData.sln  # Especifica la ruta al archivo .sln
          .\.sonar\scanner\dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
