name: SonarQube Analysis

on:
  push:
    branches:
      - main  # O cambia a la rama

jobs:
  sonar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x  # Versión de .NET

      - name: Install SonarScanner
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Restore dependencies
        run: dotnet restore TestApiNttData/TestApiNttData.sln

      - name: Build the project
        run: dotnet build TestApiNttData/TestApiNttData.sln --no-restore

      - name: Run SonarQube Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          dotnet sonarscanner begin /k:"NttDataTest" /o:"JoseGuarnizo" /d:sonar.host.url="${{ secrets.SONAR_HOST_URL }}" /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
          dotnet build TestApiNttData/TestApiNttData.sln  # Especifica la ruta al archivo .sln también en el comando build
          dotnet sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"

      - name: Run Tests (Opcional)
        run: dotnet test TestApiNttData/TestApiNttData.sln --no-build --verbosity normal
